### ISSUE TITLE
require': cannot load such file -- thwait (LoadError)

### ISSUE THREAD

**Issue by jacklim2019** [pigoz/lat#14]
ERROR when running mpv: /home/$user/.bundle/ruby/2.7.0/ruby-mpv-c415dbf0c950/lib/mpv/client.rb:207:in `require': cannot load such file -- thwait (LoadError)

This issue can be fixed by adding   
```bash
spec.add_dependency 'thwait'
```
to lat.gemspec

**Comment by pigoz** [comment]
Oops. I had this locally and didn't push it!
