### ISSUE TITLE
add configuration for other users

### ISSUE THREAD

**Issue by pigoz** [pigoz/lat#4]

**Comment by jacklim2019** [comment]
Since I'm free I've create a readme to make it more accessible to people: https://github.com/pigoz/lat/pull/13.
What is the function of text2srs and how can I use it? Does jplookup support monolingual japanese dictionary?

**Comment by pigoz** [comment]
> What is the function of text2srs and how can I use it?

It's used by `bin/clip.rb` to create cards from text (I use it for sentences from novels):

`./bin/clip.rb '適当な文' 'source'`

Can be ignored right now. I'd rather concentrate on the mpv related bits first and get those right.

> Does jplookup support monolingual japanese dictionary?

Sadly no. I want to add proper dictionary support, I really want that feature myself too, but it's not trivial.

**Comment by jacklim2019** [comment]
Hi I found it time consuming needing to choose how many contiguous subs each time I add a card to anki. How can I set the default 1 everytime I add a new card? Sorry I've no knowledge of programming at all.

**Comment by pigoz** [comment]
> Hi I found it time consuming needing to choose how many contiguous subs each time I add a card to anki. How can I set the default 1 everytime I add a new card? Sorry I've no knowledge of programming at all.

Not possibile without coding intervention. Added a related issue #15

**Comment by pigoz** [comment]
@jacklim2019 now even changing field names, or skipping the export of some fields is configurable. please check readme and let me know if you need any further configurability
